// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_MAC_Loop_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add_ln53,
        acc_q1_out,
        acc_q1_out_ap_vld,
        acc_i1_out,
        acc_i1_out_ap_vld,
        shift_i_address0,
        shift_i_ce0,
        shift_i_q0,
        c_address0,
        c_ce0,
        c_q0,
        shift_q_address0,
        shift_q_ce0,
        shift_q_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] add_ln53;
output  [15:0] acc_q1_out;
output   acc_q1_out_ap_vld;
output  [15:0] acc_i1_out;
output   acc_i1_out_ap_vld;
output  [6:0] shift_i_address0;
output   shift_i_ce0;
input  [15:0] shift_i_q0;
output  [6:0] c_address0;
output   c_ce0;
input  [4:0] c_q0;
output  [6:0] shift_q_address0;
output   shift_q_ce0;
input  [15:0] shift_q_q0;

reg ap_idle;
reg acc_q1_out_ap_vld;
reg acc_i1_out_ap_vld;
reg shift_i_ce0;
reg c_ce0;
reg shift_q_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln63_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln63_reg_285;
reg   [0:0] icmp_ln63_reg_285_pp0_iter1_reg;
reg   [0:0] icmp_ln63_reg_285_pp0_iter2_reg;
reg  signed [15:0] shift_i_load_reg_304;
reg   [4:0] c_load_reg_309;
reg  signed [15:0] shift_q_load_reg_314;
wire   [19:0] trunc_ln68_fu_203_p1;
reg   [19:0] trunc_ln68_reg_319;
wire   [19:0] trunc_ln69_fu_216_p1;
reg   [19:0] trunc_ln69_reg_324;
wire   [63:0] zext_ln68_fu_180_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_fu_165_p1;
reg   [26:0] acc_i1_fu_64;
wire   [26:0] acc_i1_3_fu_239_p2;
wire    ap_loop_init;
reg   [26:0] acc_q1_fu_68;
wire   [26:0] acc_q1_3_fu_248_p2;
reg   [7:0] i_fu_72;
wire   [7:0] add_ln63_fu_159_p2;
reg   [7:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] trunc_ln67_fu_170_p1;
wire   [6:0] idx_fu_174_p2;
wire  signed [4:0] mul_ln68_fu_197_p0;
wire  signed [20:0] sext_ln68_1_fu_194_p1;
wire   [20:0] mul_ln68_fu_197_p2;
wire  signed [4:0] mul_ln69_fu_210_p1;
wire   [20:0] mul_ln69_fu_210_p2;
wire  signed [26:0] sext_ln68_2_fu_236_p1;
wire  signed [26:0] sext_ln69_1_fu_245_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 acc_i1_fu_64 = 27'd0;
#0 acc_q1_fu_68 = 27'd0;
#0 i_fu_72 = 8'd0;
#0 ap_done_reg = 1'b0;
end

fir_mul_5s_16s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 21 ))
mul_5s_16s_21_1_1_U11(
    .din0(mul_ln68_fu_197_p0),
    .din1(shift_i_load_reg_304),
    .dout(mul_ln68_fu_197_p2)
);

fir_mul_16s_5s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 21 ))
mul_16s_5s_21_1_1_U12(
    .din0(shift_q_load_reg_314),
    .din1(mul_ln69_fu_210_p1),
    .dout(mul_ln69_fu_210_p2)
);

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_i1_fu_64 <= 27'd0;
        end else if (((icmp_ln63_reg_285_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            acc_i1_fu_64 <= acc_i1_3_fu_239_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_q1_fu_68 <= 27'd0;
        end else if (((icmp_ln63_reg_285_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            acc_q1_fu_68 <= acc_q1_3_fu_248_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln63_fu_153_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_72 <= add_ln63_fu_159_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        c_load_reg_309 <= c_q0;
        icmp_ln63_reg_285 <= icmp_ln63_fu_153_p2;
        icmp_ln63_reg_285_pp0_iter1_reg <= icmp_ln63_reg_285;
        shift_i_load_reg_304 <= shift_i_q0;
        shift_q_load_reg_314 <= shift_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln63_reg_285_pp0_iter2_reg <= icmp_ln63_reg_285_pp0_iter1_reg;
        trunc_ln68_reg_319 <= trunc_ln68_fu_203_p1;
        trunc_ln69_reg_324 <= trunc_ln69_fu_216_p1;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_285_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_i1_out_ap_vld = 1'b1;
    end else begin
        acc_i1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_reg_285_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_q1_out_ap_vld = 1'b1;
    end else begin
        acc_q1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_fu_153_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_i_ce0 = 1'b1;
    end else begin
        shift_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_q_ce0 = 1'b1;
    end else begin
        shift_q_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_i1_3_fu_239_p2 = ($signed(sext_ln68_2_fu_236_p1) + $signed(acc_i1_fu_64));

assign acc_i1_out = acc_i1_fu_64[15:0];

assign acc_q1_3_fu_248_p2 = ($signed(sext_ln69_1_fu_245_p1) + $signed(acc_q1_fu_68));

assign acc_q1_out = acc_q1_fu_68[15:0];

assign add_ln63_fu_159_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign c_address0 = zext_ln63_fu_165_p1;

assign icmp_ln63_fu_153_p2 = ((ap_sig_allocacmp_i_1 == 8'd128) ? 1'b1 : 1'b0);

assign idx_fu_174_p2 = (add_ln53 - trunc_ln67_fu_170_p1);

assign mul_ln68_fu_197_p0 = sext_ln68_1_fu_194_p1;

assign mul_ln69_fu_210_p1 = sext_ln68_1_fu_194_p1;

assign sext_ln68_1_fu_194_p1 = $signed(c_load_reg_309);

assign sext_ln68_2_fu_236_p1 = $signed(trunc_ln68_reg_319);

assign sext_ln69_1_fu_245_p1 = $signed(trunc_ln69_reg_324);

assign shift_i_address0 = zext_ln68_fu_180_p1;

assign shift_q_address0 = zext_ln68_fu_180_p1;

assign trunc_ln67_fu_170_p1 = ap_sig_allocacmp_i_1[6:0];

assign trunc_ln68_fu_203_p1 = mul_ln68_fu_197_p2[19:0];

assign trunc_ln69_fu_216_p1 = mul_ln69_fu_210_p2[19:0];

assign zext_ln63_fu_165_p1 = ap_sig_allocacmp_i_1;

assign zext_ln68_fu_180_p1 = idx_fu_174_p2;

endmodule //fir_fir_Pipeline_MAC_Loop_1
