-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fir_fir_Pipeline_MAC_Loop_c_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 5; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 128
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of fir_fir_Pipeline_MAC_Loop_c_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01010", 1 => "01011", 2 => "01011", 3 => "01000", 
    4 => "00011", 5 => "11101", 6 => "11000", 7 => "10101", 
    8 => "10101", 9 => "10110", 10 => "10110", 11 => "10110", 
    12 => "10110", 13 => "10110", 14 => "10110", 15 => "10110", 
    16 => "10110", 17 => "10110", 18 => "10110", 19 => "10110", 
    20 => "10110", 21 => "10110", 22 => "10110", 23 => "10110", 
    24 => "10110", 25 => "10110", 26 => "10110", 27 => "10110", 
    28 => "10110", 29 => "10110", 30 => "10110", 31 => "10110", 
    32 => "10110", 33 => "10101", 34 => "10101", 35 => "11000", 
    36 => "11101", 37 => "00011", 38 => "01000", 39 => "01011", 
    40 => "01011", 41 => "01010", 42 => "01010", 43 => "01010", 
    44 => "01010", 45 => "01010", 46 => "01010", 47 => "01010", 
    48 => "01010", 49 => "01011", 50 => "01011", 51 => "01000", 
    52 => "00011", 53 => "11101", 54 => "11000", 55 => "10101", 
    56 => "10101", 57 => "10110", 58 => "10110", 59 => "10110", 
    60 => "10110", 61 => "10110", 62 => "10110", 63 => "10110", 
    64 => "10110", 65 => "10101", 66 => "10101", 67 => "11000", 
    68 => "11101", 69 => "00011", 70 => "01000", 71 => "01011", 
    72 => "01011", 73 => "01010", 74 => "01010", 75 => "01010", 
    76 => "01010", 77 => "01010", 78 => "01010", 79 => "01010", 
    80 => "01010", 81 => "01011", 82 => "01011", 83 => "01000", 
    84 => "00011", 85 => "11101", 86 => "11000", 87 => "10101", 
    88 => "10101", 89 => "10110", 90 => "10110", 91 => "10110", 
    92 => "10110", 93 => "10110", 94 => "10110", 95 => "10110", 
    96 => "10110", 97 => "10101", 98 => "10101", 99 => "11000", 
    100 => "11101", 101 => "00011", 102 => "01000", 103 => "01011", 
    104 => "01011", 105 => "01010", 106 => "01010", 107 => "01010", 
    108 => "01010", 109 => "01010", 110 => "01010", 111 => "01010", 
    112 => "01010", 113 => "01010", 114 => "01010", 115 => "01010", 
    116 => "01010", 117 => "01010", 118 => "01010", 119 => "01010", 
    120 => "01010", 121 => "01010", 122 => "01010", 123 => "01010", 
    124 => "01010", 125 => "01010", 126 => "01010", 127 => "01010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

