-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 9;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    y_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    y_TVALID : OUT STD_LOGIC;
    y_TREADY : IN STD_LOGIC;
    y_TKEEP : OUT STD_LOGIC_VECTOR (7 downto 0);
    y_TSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    y_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    x_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    x_TVALID : IN STD_LOGIC;
    x_TREADY : OUT STD_LOGIC;
    x_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    x_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    x_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of fir is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_fir,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg225-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=1678,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=660,HLS_SYN_LUT=812,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal coeffs_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal shift_i_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_i_ce0 : STD_LOGIC;
    signal shift_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shift_i_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_i_ce1 : STD_LOGIC;
    signal shift_i_we1 : STD_LOGIC;
    signal shift_i_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shift_q_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_q_ce0 : STD_LOGIC;
    signal shift_q_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shift_q_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_q_ce1 : STD_LOGIC;
    signal shift_q_we1 : STD_LOGIC;
    signal shift_q_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal x_TDATA_blk_n : STD_LOGIC;
    signal in_sample_keep_reg_377 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_sample_last_reg_382 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptr0_reg_387 : STD_LOGIC_VECTOR (6 downto 0);
    signal i1_reg_393 : STD_LOGIC_VECTOR (15 downto 0);
    signal q1_reg_398 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptr1_fu_317_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ptr1_reg_403 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal c_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_ce0 : STD_LOGIC;
    signal c_we0 : STD_LOGIC;
    signal c_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_1_ce0 : STD_LOGIC;
    signal c_1_we0 : STD_LOGIC;
    signal c_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_idle : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_ready : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_we0 : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_we0 : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_idle : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_ready : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_c_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_c_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out_ap_vld : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out_ap_vld : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_idle : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_ready : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_c_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_c_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out_ap_vld : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out_ap_vld : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call25 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal acc_q0_loc_fu_120 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_i0_loc_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm_state6 : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal acc_q1_loc_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_i1_loc_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln37_fu_279_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln50_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln62_fu_305_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i0_fu_259_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_y_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state9 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal y_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal y_TVALID_int_regslice : STD_LOGIC;
    signal y_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal y_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_y_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_apdone_blk : STD_LOGIC;
    signal x_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal x_TVALID_int_regslice : STD_LOGIC;
    signal x_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal x_TKEEP_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_x_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal x_TSTRB_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal regslice_both_x_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_apdone_blk : STD_LOGIC;
    signal x_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_fir_Pipeline_VITIS_LOOP_13_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        c_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_1_ce0 : OUT STD_LOGIC;
        c_1_we0 : OUT STD_LOGIC;
        c_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_we0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        coeffs_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        coeffs_ce0 : OUT STD_LOGIC;
        coeffs_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_fir_Pipeline_MAC_Loop_0 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr0 : IN STD_LOGIC_VECTOR (6 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        c_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_1_ce0 : OUT STD_LOGIC;
        c_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        acc_q0_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_q0_out_ap_vld : OUT STD_LOGIC;
        acc_i0_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_i0_out_ap_vld : OUT STD_LOGIC;
        shift_i_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        shift_i_ce0 : OUT STD_LOGIC;
        shift_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        shift_q_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        shift_q_ce0 : OUT STD_LOGIC;
        shift_q_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_fir_Pipeline_MAC_Loop_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr1 : IN STD_LOGIC_VECTOR (6 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        c_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        c_1_ce0 : OUT STD_LOGIC;
        c_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        acc_q1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_q1_out_ap_vld : OUT STD_LOGIC;
        acc_i1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_i1_out_ap_vld : OUT STD_LOGIC;
        shift_i_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        shift_i_ce0 : OUT STD_LOGIC;
        shift_i_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        shift_q_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        shift_q_ce0 : OUT STD_LOGIC;
        shift_q_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_shift_i_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_c_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        coeffs_address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        coeffs_ce0 : IN STD_LOGIC;
        coeffs_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component fir_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    shift_i_U : component fir_shift_i_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => shift_i_address0,
        ce0 => shift_i_ce0,
        q0 => shift_i_q0,
        address1 => shift_i_address1,
        ce1 => shift_i_ce1,
        we1 => shift_i_we1,
        d1 => shift_i_d1);

    shift_q_U : component fir_shift_i_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => shift_q_address0,
        ce0 => shift_q_ce0,
        q0 => shift_q_q0,
        address1 => shift_q_address1,
        ce1 => shift_q_ce1,
        we1 => shift_q_we1,
        d1 => shift_q_d1);

    c_U : component fir_c_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => c_address0,
        ce0 => c_ce0,
        we0 => c_we0,
        d0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_d0,
        q0 => c_q0);

    c_1_U : component fir_c_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => c_1_address0,
        ce0 => c_1_ce0,
        we0 => c_1_we0,
        d0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_d0,
        q0 => c_1_q0);

    grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211 : component fir_fir_Pipeline_VITIS_LOOP_13_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start,
        ap_done => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done,
        ap_idle => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_idle,
        ap_ready => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_ready,
        c_1_address0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_address0,
        c_1_ce0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_ce0,
        c_1_we0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_we0,
        c_1_d0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_d0,
        c_address0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_address0,
        c_ce0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_ce0,
        c_we0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_we0,
        c_d0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_d0,
        coeffs_address0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_address0,
        coeffs_ce0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_ce0,
        coeffs_q0 => coeffs_q0);

    grp_fir_Pipeline_MAC_Loop_0_fu_221 : component fir_fir_Pipeline_MAC_Loop_0
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start,
        ap_done => grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done,
        ap_idle => grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_idle,
        ap_ready => grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_ready,
        ptr0 => ptr0_reg_387,
        c_address0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_c_address0,
        c_ce0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_c_ce0,
        c_q0 => c_q0,
        c_1_address0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_address0,
        c_1_ce0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_ce0,
        c_1_q0 => c_1_q0,
        acc_q0_out => grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out,
        acc_q0_out_ap_vld => grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out_ap_vld,
        acc_i0_out => grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out,
        acc_i0_out_ap_vld => grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out_ap_vld,
        shift_i_address0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_address0,
        shift_i_ce0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_ce0,
        shift_i_q0 => shift_i_q0,
        shift_q_address0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_address0,
        shift_q_ce0 => grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_ce0,
        shift_q_q0 => shift_q_q0);

    grp_fir_Pipeline_MAC_Loop_1_fu_234 : component fir_fir_Pipeline_MAC_Loop_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start,
        ap_done => grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done,
        ap_idle => grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_idle,
        ap_ready => grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_ready,
        ptr1 => ptr1_reg_403,
        c_address0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_c_address0,
        c_ce0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_c_ce0,
        c_q0 => c_q0,
        c_1_address0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_address0,
        c_1_ce0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_ce0,
        c_1_q0 => c_1_q0,
        acc_q1_out => grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out,
        acc_q1_out_ap_vld => grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out_ap_vld,
        acc_i1_out => grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out,
        acc_i1_out_ap_vld => grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out_ap_vld,
        shift_i_address0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_address0,
        shift_i_ce0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_ce0,
        shift_i_q0 => shift_i_q0,
        shift_q_address0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_address0,
        shift_q_ce0 => grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_ce0,
        shift_q_q0 => shift_q_q0);

    control_s_axi_U : component fir_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        coeffs_address0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_address0,
        coeffs_ce0 => grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_coeffs_ce0,
        coeffs_q0 => coeffs_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_y_V_data_V_U : component fir_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_TDATA_int_regslice,
        vld_in => y_TVALID_int_regslice,
        ack_in => y_TREADY_int_regslice,
        data_out => y_TDATA,
        vld_out => regslice_both_y_V_data_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_data_V_U_apdone_blk);

    regslice_both_y_V_keep_V_U : component fir_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_sample_keep_reg_377,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_keep_V_U_ack_in_dummy,
        data_out => y_TKEEP,
        vld_out => regslice_both_y_V_keep_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_keep_V_U_apdone_blk);

    regslice_both_y_V_strb_V_U : component fir_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_TSTRB_int_regslice,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_strb_V_U_ack_in_dummy,
        data_out => y_TSTRB,
        vld_out => regslice_both_y_V_strb_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_strb_V_U_apdone_blk);

    regslice_both_y_V_last_V_U : component fir_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_sample_last_reg_382,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_last_V_U_ack_in_dummy,
        data_out => y_TLAST,
        vld_out => regslice_both_y_V_last_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_last_V_U_apdone_blk);

    regslice_both_x_V_data_V_U : component fir_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TDATA,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_data_V_U_ack_in,
        data_out => x_TDATA_int_regslice,
        vld_out => x_TVALID_int_regslice,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_data_V_U_apdone_blk);

    regslice_both_x_V_keep_V_U : component fir_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TKEEP,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_keep_V_U_ack_in,
        data_out => x_TKEEP_int_regslice,
        vld_out => regslice_both_x_V_keep_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_keep_V_U_apdone_blk);

    regslice_both_x_V_strb_V_U : component fir_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TSTRB,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_strb_V_U_ack_in,
        data_out => x_TSTRB_int_regslice,
        vld_out => regslice_both_x_V_strb_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_strb_V_U_apdone_blk);

    regslice_both_x_V_last_V_U : component fir_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TLAST,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_last_V_U_ack_in,
        data_out => x_TLAST_int_regslice,
        vld_out => regslice_both_x_V_last_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_ready = ap_const_logic_1)) then 
                    grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state6) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_ready = ap_const_logic_1)) then 
                    grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call25) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_ready = ap_const_logic_1)) then 
                    grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out_ap_vld = ap_const_logic_1))) then
                acc_i0_loc_fu_116 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_i0_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out_ap_vld = ap_const_logic_1))) then
                acc_i1_loc_fu_108 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_i1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out_ap_vld = ap_const_logic_1))) then
                acc_q0_loc_fu_120 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_acc_q0_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out_ap_vld = ap_const_logic_1))) then
                acc_q1_loc_fu_112 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_acc_q1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                i1_reg_393 <= x_TDATA_int_regslice(47 downto 32);
                in_sample_keep_reg_377 <= x_TKEEP_int_regslice;
                in_sample_last_reg_382 <= x_TLAST_int_regslice;
                ptr0_reg_387 <= ptr;
                q1_reg_398 <= x_TDATA_int_regslice(63 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ptr <= add_ln62_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                ptr1_reg_403 <= ptr1_fu_317_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state8, ap_CS_fsm_state9, grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done, grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done, grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7, ap_block_state1, ap_block_state9, y_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((y_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((y_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln62_fu_305_p2 <= std_logic_vector(unsigned(ptr) + unsigned(ap_const_lv7_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);
    ap_NS_fsm_state6 <= ap_NS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done)
    begin
        if ((grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done)
    begin
        if ((grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done)
    begin
        if ((grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(y_TREADY_int_regslice)
    begin
        if ((y_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9, y_TREADY_int_regslice)
    begin
        if (((y_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, x_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((x_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call25_assign_proc : process(ap_start, x_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call25 <= ((x_TVALID_int_regslice = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state9_assign_proc : process(regslice_both_y_V_data_V_U_apdone_blk, y_TREADY_int_regslice)
    begin
                ap_block_state9 <= ((y_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state9, ap_block_state9, y_TREADY_int_regslice)
    begin
        if ((not(((y_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9, ap_block_state9, y_TREADY_int_regslice)
    begin
        if ((not(((y_TREADY_int_regslice = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    c_1_address0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_address0, grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_address0, grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            c_1_address0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_1_address0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_1_address0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_address0;
        else 
            c_1_address0 <= "XXXXXX";
        end if; 
    end process;


    c_1_ce0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_ce0, grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_ce0, grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            c_1_ce0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_c_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_1_ce0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_c_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_1_ce0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_ce0;
        else 
            c_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_1_we0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_1_we0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_1_we0;
        else 
            c_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    c_address0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_address0, grp_fir_Pipeline_MAC_Loop_0_fu_221_c_address0, grp_fir_Pipeline_MAC_Loop_1_fu_234_c_address0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            c_address0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_c_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_address0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_c_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_address0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_address0;
        else 
            c_address0 <= "XXXXXX";
        end if; 
    end process;


    c_ce0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_ce0, grp_fir_Pipeline_MAC_Loop_0_fu_221_c_ce0, grp_fir_Pipeline_MAC_Loop_1_fu_234_c_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            c_ce0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_c_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_ce0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_c_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_ce0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_ce0;
        else 
            c_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_we0_assign_proc : process(grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_we0 <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_c_we0;
        else 
            c_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start <= grp_fir_Pipeline_MAC_Loop_0_fu_221_ap_start_reg;
    grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start <= grp_fir_Pipeline_MAC_Loop_1_fu_234_ap_start_reg;
    grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start <= grp_fir_Pipeline_VITIS_LOOP_13_1_fu_211_ap_start_reg;
    i0_fu_259_p1 <= x_TDATA_int_regslice(16 - 1 downto 0);
    ptr1_fu_317_p2 <= std_logic_vector(unsigned(ptr0_reg_387) + unsigned(ap_const_lv7_1));

    shift_i_address0_assign_proc : process(grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_address0, grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_address0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            shift_i_address0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            shift_i_address0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_address0;
        else 
            shift_i_address0 <= "XXXXXXX";
        end if; 
    end process;


    shift_i_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, zext_ln37_fu_279_p1, zext_ln50_fu_322_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_i_address1 <= zext_ln50_fu_322_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            shift_i_address1 <= zext_ln37_fu_279_p1(7 - 1 downto 0);
        else 
            shift_i_address1 <= "XXXXXXX";
        end if; 
    end process;


    shift_i_ce0_assign_proc : process(grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_ce0, grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_ce0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            shift_i_ce0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_i_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            shift_i_ce0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_i_ce0;
        else 
            shift_i_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    shift_i_ce1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            shift_i_ce1 <= ap_const_logic_1;
        else 
            shift_i_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    shift_i_d1_assign_proc : process(ap_CS_fsm_state1, i1_reg_393, ap_CS_fsm_state5, i0_fu_259_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_i_d1 <= i1_reg_393;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            shift_i_d1 <= i0_fu_259_p1;
        else 
            shift_i_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    shift_i_we1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            shift_i_we1 <= ap_const_logic_1;
        else 
            shift_i_we1 <= ap_const_logic_0;
        end if; 
    end process;


    shift_q_address0_assign_proc : process(grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_address0, grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_address0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            shift_q_address0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            shift_q_address0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_address0;
        else 
            shift_q_address0 <= "XXXXXXX";
        end if; 
    end process;


    shift_q_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, zext_ln37_fu_279_p1, zext_ln50_fu_322_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_q_address1 <= zext_ln50_fu_322_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            shift_q_address1 <= zext_ln37_fu_279_p1(7 - 1 downto 0);
        else 
            shift_q_address1 <= "XXXXXXX";
        end if; 
    end process;


    shift_q_ce0_assign_proc : process(grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_ce0, grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_ce0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            shift_q_ce0 <= grp_fir_Pipeline_MAC_Loop_1_fu_234_shift_q_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            shift_q_ce0 <= grp_fir_Pipeline_MAC_Loop_0_fu_221_shift_q_ce0;
        else 
            shift_q_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    shift_q_ce1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            shift_q_ce1 <= ap_const_logic_1;
        else 
            shift_q_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    shift_q_d1_assign_proc : process(ap_CS_fsm_state1, q1_reg_398, ap_CS_fsm_state5, x_TDATA_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_q_d1 <= q1_reg_398;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            shift_q_d1 <= x_TDATA_int_regslice(31 downto 16);
        else 
            shift_q_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    shift_q_we1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            shift_q_we1 <= ap_const_logic_1;
        else 
            shift_q_we1 <= ap_const_logic_0;
        end if; 
    end process;


    x_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, x_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            x_TDATA_blk_n <= x_TVALID_int_regslice;
        else 
            x_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_TREADY <= regslice_both_x_V_data_V_U_ack_in;

    x_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_TREADY_int_regslice <= ap_const_logic_1;
        else 
            x_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, y_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            y_TDATA_blk_n <= y_TREADY_int_regslice;
        else 
            y_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y_TDATA_int_regslice <= (((acc_q1_loc_fu_112 & acc_i1_loc_fu_108) & acc_q0_loc_fu_120) & acc_i0_loc_fu_116);
    y_TSTRB_int_regslice <= "XXXXXXXX";
    y_TVALID <= regslice_both_y_V_data_V_U_vld_out;

    y_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state8, y_TREADY_int_regslice)
    begin
        if (((y_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            y_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln37_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ptr),64));
    zext_ln50_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ptr1_fu_317_p2),64));
end behav;
