-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    y_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    y_TVALID : OUT STD_LOGIC;
    y_TREADY : IN STD_LOGIC;
    y_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    y_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    y_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    x_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    x_TVALID : IN STD_LOGIC;
    x_TREADY : OUT STD_LOGIC;
    x_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    x_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    x_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of fir is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_fir,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.712000,HLS_SYN_LAT=137,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=153,HLS_SYN_LUT=234,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ptr : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal shift_reg_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal shift_reg_ce0 : STD_LOGIC;
    signal shift_reg_we0 : STD_LOGIC;
    signal shift_reg_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal x_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_sample_keep_reg_166 : STD_LOGIC_VECTOR (1 downto 0);
    signal in_sample_last_reg_171 : STD_LOGIC_VECTOR (0 downto 0);
    signal ptr_load_reg_176 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_fu_112_ap_start : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_ap_done : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_ap_idle : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_ap_ready : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_acc_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_fu_112_acc_out_ap_vld : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_ce0 : STD_LOGIC;
    signal grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal acc_loc_fu_66 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln23_fu_139_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln34_fu_144_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_y_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal y_TVALID_int_regslice : STD_LOGIC;
    signal y_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_y_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal y_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_y_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_y_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_apdone_blk : STD_LOGIC;
    signal x_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal x_TVALID_int_regslice : STD_LOGIC;
    signal x_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_x_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal x_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal x_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_x_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_apdone_blk : STD_LOGIC;
    signal x_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_x_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_x_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_fir_Pipeline_MAC_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ptr_load : IN STD_LOGIC_VECTOR (6 downto 0);
        acc_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        acc_out_ap_vld : OUT STD_LOGIC;
        shift_reg_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        shift_reg_ce0 : OUT STD_LOGIC;
        shift_reg_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_shift_reg_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    shift_reg_U : component fir_shift_reg_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => shift_reg_address0,
        ce0 => shift_reg_ce0,
        we0 => shift_reg_we0,
        d0 => x_TDATA_int_regslice,
        q0 => shift_reg_q0);

    grp_fir_Pipeline_MAC_Loop_fu_112 : component fir_fir_Pipeline_MAC_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_fir_Pipeline_MAC_Loop_fu_112_ap_start,
        ap_done => grp_fir_Pipeline_MAC_Loop_fu_112_ap_done,
        ap_idle => grp_fir_Pipeline_MAC_Loop_fu_112_ap_idle,
        ap_ready => grp_fir_Pipeline_MAC_Loop_fu_112_ap_ready,
        ptr_load => ptr_load_reg_176,
        acc_out => grp_fir_Pipeline_MAC_Loop_fu_112_acc_out,
        acc_out_ap_vld => grp_fir_Pipeline_MAC_Loop_fu_112_acc_out_ap_vld,
        shift_reg_address0 => grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_address0,
        shift_reg_ce0 => grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_ce0,
        shift_reg_q0 => shift_reg_q0);

    regslice_both_y_V_data_V_U : component fir_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => acc_loc_fu_66,
        vld_in => y_TVALID_int_regslice,
        ack_in => y_TREADY_int_regslice,
        data_out => y_TDATA,
        vld_out => regslice_both_y_V_data_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_data_V_U_apdone_blk);

    regslice_both_y_V_keep_V_U : component fir_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_sample_keep_reg_166,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_keep_V_U_ack_in_dummy,
        data_out => y_TKEEP,
        vld_out => regslice_both_y_V_keep_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_keep_V_U_apdone_blk);

    regslice_both_y_V_strb_V_U : component fir_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => y_TSTRB_int_regslice,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_strb_V_U_ack_in_dummy,
        data_out => y_TSTRB,
        vld_out => regslice_both_y_V_strb_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_strb_V_U_apdone_blk);

    regslice_both_y_V_last_V_U : component fir_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_sample_last_reg_171,
        vld_in => y_TVALID_int_regslice,
        ack_in => regslice_both_y_V_last_V_U_ack_in_dummy,
        data_out => y_TLAST,
        vld_out => regslice_both_y_V_last_V_U_vld_out,
        ack_out => y_TREADY,
        apdone_blk => regslice_both_y_V_last_V_U_apdone_blk);

    regslice_both_x_V_data_V_U : component fir_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TDATA,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_data_V_U_ack_in,
        data_out => x_TDATA_int_regslice,
        vld_out => x_TVALID_int_regslice,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_data_V_U_apdone_blk);

    regslice_both_x_V_keep_V_U : component fir_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TKEEP,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_keep_V_U_ack_in,
        data_out => x_TKEEP_int_regslice,
        vld_out => regslice_both_x_V_keep_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_keep_V_U_apdone_blk);

    regslice_both_x_V_strb_V_U : component fir_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TSTRB,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_strb_V_U_ack_in,
        data_out => x_TSTRB_int_regslice,
        vld_out => regslice_both_x_V_strb_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_strb_V_U_apdone_blk);

    regslice_both_x_V_last_V_U : component fir_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => x_TLAST,
        vld_in => x_TVALID,
        ack_in => regslice_both_x_V_last_V_U_ack_in,
        data_out => x_TLAST_int_regslice,
        vld_out => regslice_both_x_V_last_V_U_vld_out,
        ack_out => x_TREADY_int_regslice,
        apdone_blk => regslice_both_x_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fir_Pipeline_MAC_Loop_fu_112_ap_ready = ap_const_logic_1)) then 
                    grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_fir_Pipeline_MAC_Loop_fu_112_acc_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                acc_loc_fu_66 <= grp_fir_Pipeline_MAC_Loop_fu_112_acc_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                in_sample_keep_reg_166 <= x_TKEEP_int_regslice;
                in_sample_last_reg_171 <= x_TLAST_int_regslice;
                ptr_load_reg_176 <= ptr;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((x_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ptr <= add_ln34_fu_144_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state1, grp_fir_Pipeline_MAC_Loop_fu_112_ap_done, ap_CS_fsm_state3, ap_block_state5, y_TREADY_int_regslice, x_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((x_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_fir_Pipeline_MAC_Loop_fu_112_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (y_TREADY_int_regslice = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((ap_const_boolean_1 = ap_block_state5) or (y_TREADY_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln34_fu_144_p2 <= std_logic_vector(unsigned(ptr) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(x_TVALID_int_regslice)
    begin
        if ((x_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_fir_Pipeline_MAC_Loop_fu_112_ap_done)
    begin
        if ((grp_fir_Pipeline_MAC_Loop_fu_112_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(y_TREADY_int_regslice)
    begin
        if ((y_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5, y_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state5) or (y_TREADY_int_regslice = ap_const_logic_0))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_assign_proc : process(regslice_both_y_V_data_V_U_apdone_blk, y_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((y_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_y_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_fir_Pipeline_MAC_Loop_fu_112_ap_start <= grp_fir_Pipeline_MAC_Loop_fu_112_ap_start_reg;

    shift_reg_address0_assign_proc : process(ap_CS_fsm_state1, grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_address0, ap_CS_fsm_state3, zext_ln23_fu_139_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            shift_reg_address0 <= zext_ln23_fu_139_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            shift_reg_address0 <= grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_address0;
        else 
            shift_reg_address0 <= "XXXXXXX";
        end if; 
    end process;


    shift_reg_ce0_assign_proc : process(ap_CS_fsm_state1, grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_ce0, ap_CS_fsm_state3, x_TVALID_int_regslice)
    begin
        if (((x_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            shift_reg_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            shift_reg_ce0 <= grp_fir_Pipeline_MAC_Loop_fu_112_shift_reg_ce0;
        else 
            shift_reg_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    shift_reg_we0_assign_proc : process(ap_CS_fsm_state1, x_TVALID_int_regslice)
    begin
        if (((x_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            shift_reg_we0 <= ap_const_logic_1;
        else 
            shift_reg_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, x_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            x_TDATA_blk_n <= x_TVALID_int_regslice;
        else 
            x_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_TREADY <= regslice_both_x_V_data_V_U_ack_in;

    x_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, x_TVALID_int_regslice)
    begin
        if (((x_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_TREADY_int_regslice <= ap_const_logic_1;
        else 
            x_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    y_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, y_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            y_TDATA_blk_n <= y_TREADY_int_regslice;
        else 
            y_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    y_TSTRB_int_regslice <= "XX";
    y_TVALID <= regslice_both_y_V_data_V_U_vld_out;

    y_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, y_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (y_TREADY_int_regslice = ap_const_logic_1))) then 
            y_TVALID_int_regslice <= ap_const_logic_1;
        else 
            y_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln23_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ptr),64));
end behav;
