// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.168000,HLS_SYN_LAT=263,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2235,HLS_SYN_LUT=905,HLS_VERSION=2023_2}" *)

module fir (
        ap_clk,
        ap_rst_n,
        y_TDATA,
        y_TVALID,
        y_TREADY,
        y_TKEEP,
        y_TSTRB,
        y_TLAST,
        x_TDATA,
        x_TVALID,
        x_TREADY,
        x_TKEEP,
        x_TSTRB,
        x_TLAST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
output  [15:0] y_TDATA;
output   y_TVALID;
input   y_TREADY;
output  [1:0] y_TKEEP;
output  [1:0] y_TSTRB;
output  [0:0] y_TLAST;
input  [15:0] x_TDATA;
input   x_TVALID;
output   x_TREADY;
input  [1:0] x_TKEEP;
input  [1:0] x_TSTRB;
input  [0:0] x_TLAST;

 reg    ap_rst_n_inv;
reg    y_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    x_TDATA_blk_n;
wire    ap_CS_fsm_state1;
reg   [15:0] in_sample_data_reg_670;
reg   [1:0] in_sample_keep_reg_675;
reg   [0:0] in_sample_last_reg_680;
wire   [19:0] mul_i29_fu_653_p2;
reg   [19:0] mul_i29_reg_685;
wire    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start;
wire    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_done;
wire    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_idle;
wire    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_ready;
wire   [15:0] grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out;
wire    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out_ap_vld;
reg    grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [15:0] acc_loc_fu_320;
wire   [18:0] p_shl_fu_629_p3;
wire   [16:0] p_shl1_fu_641_p3;
wire  signed [19:0] p_shl_cast_fu_637_p1;
wire  signed [19:0] p_shl1_cast_fu_649_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_y_V_data_V_U_apdone_blk;
reg    ap_block_state4;
reg    y_TVALID_int_regslice;
wire    y_TREADY_int_regslice;
wire    regslice_both_y_V_data_V_U_vld_out;
wire    regslice_both_y_V_keep_V_U_apdone_blk;
wire    regslice_both_y_V_keep_V_U_ack_in_dummy;
wire    regslice_both_y_V_keep_V_U_vld_out;
wire    regslice_both_y_V_strb_V_U_apdone_blk;
wire   [1:0] y_TSTRB_int_regslice;
wire    regslice_both_y_V_strb_V_U_ack_in_dummy;
wire    regslice_both_y_V_strb_V_U_vld_out;
wire    regslice_both_y_V_last_V_U_apdone_blk;
wire    regslice_both_y_V_last_V_U_ack_in_dummy;
wire    regslice_both_y_V_last_V_U_vld_out;
wire    regslice_both_x_V_data_V_U_apdone_blk;
wire   [15:0] x_TDATA_int_regslice;
wire    x_TVALID_int_regslice;
reg    x_TREADY_int_regslice;
wire    regslice_both_x_V_data_V_U_ack_in;
wire    regslice_both_x_V_keep_V_U_apdone_blk;
wire   [1:0] x_TKEEP_int_regslice;
wire    regslice_both_x_V_keep_V_U_vld_out;
wire    regslice_both_x_V_keep_V_U_ack_in;
wire    regslice_both_x_V_strb_V_U_apdone_blk;
wire   [1:0] x_TSTRB_int_regslice;
wire    regslice_both_x_V_strb_V_U_vld_out;
wire    regslice_both_x_V_strb_V_U_ack_in;
wire    regslice_both_x_V_last_V_U_apdone_blk;
wire   [0:0] x_TLAST_int_regslice;
wire    regslice_both_x_V_last_V_U_vld_out;
wire    regslice_both_x_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg = 1'b0;
end

fir_fir_Pipeline_Shift_Accum_Loop grp_fir_Pipeline_Shift_Accum_Loop_fu_353(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start),
    .ap_done(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_done),
    .ap_idle(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_idle),
    .ap_ready(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_ready),
    .mul_i29(mul_i29_reg_685),
    .in_sample_data(in_sample_data_reg_670),
    .acc_out(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out),
    .acc_out_ap_vld(grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out_ap_vld)
);

fir_regslice_both #(
    .DataWidth( 16 ))
regslice_both_y_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(acc_loc_fu_320),
    .vld_in(y_TVALID_int_regslice),
    .ack_in(y_TREADY_int_regslice),
    .data_out(y_TDATA),
    .vld_out(regslice_both_y_V_data_V_U_vld_out),
    .ack_out(y_TREADY),
    .apdone_blk(regslice_both_y_V_data_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 2 ))
regslice_both_y_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_keep_reg_675),
    .vld_in(y_TVALID_int_regslice),
    .ack_in(regslice_both_y_V_keep_V_U_ack_in_dummy),
    .data_out(y_TKEEP),
    .vld_out(regslice_both_y_V_keep_V_U_vld_out),
    .ack_out(y_TREADY),
    .apdone_blk(regslice_both_y_V_keep_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 2 ))
regslice_both_y_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(y_TSTRB_int_regslice),
    .vld_in(y_TVALID_int_regslice),
    .ack_in(regslice_both_y_V_strb_V_U_ack_in_dummy),
    .data_out(y_TSTRB),
    .vld_out(regslice_both_y_V_strb_V_U_vld_out),
    .ack_out(y_TREADY),
    .apdone_blk(regslice_both_y_V_strb_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 1 ))
regslice_both_y_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_last_reg_680),
    .vld_in(y_TVALID_int_regslice),
    .ack_in(regslice_both_y_V_last_V_U_ack_in_dummy),
    .data_out(y_TLAST),
    .vld_out(regslice_both_y_V_last_V_U_vld_out),
    .ack_out(y_TREADY),
    .apdone_blk(regslice_both_y_V_last_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 16 ))
regslice_both_x_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_TDATA),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_data_V_U_ack_in),
    .data_out(x_TDATA_int_regslice),
    .vld_out(x_TVALID_int_regslice),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_data_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 2 ))
regslice_both_x_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_TKEEP),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_keep_V_U_ack_in),
    .data_out(x_TKEEP_int_regslice),
    .vld_out(regslice_both_x_V_keep_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_keep_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 2 ))
regslice_both_x_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_TSTRB),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_strb_V_U_ack_in),
    .data_out(x_TSTRB_int_regslice),
    .vld_out(regslice_both_x_V_strb_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_strb_V_U_apdone_blk)
);

fir_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_TLAST),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_last_V_U_ack_in),
    .data_out(x_TLAST_int_regslice),
    .vld_out(regslice_both_x_V_last_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg <= 1'b0;
    end else begin
        if (((x_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        acc_loc_fu_320 <= grp_fir_Pipeline_Shift_Accum_Loop_fu_353_acc_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_sample_data_reg_670 <= x_TDATA_int_regslice;
        in_sample_keep_reg_675 <= x_TKEEP_int_regslice;
        in_sample_last_reg_680 <= x_TLAST_int_regslice;
        mul_i29_reg_685[19 : 1] <= mul_i29_fu_653_p2[19 : 1];
    end
end

always @ (*) begin
    if ((x_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((y_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((y_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        x_TDATA_blk_n = x_TVALID_int_regslice;
    end else begin
        x_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((x_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_TREADY_int_regslice = 1'b1;
    end else begin
        x_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        y_TDATA_blk_n = y_TREADY_int_regslice;
    end else begin
        y_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((y_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        y_TVALID_int_regslice = 1'b1;
    end else begin
        y_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((x_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((y_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((y_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((y_TREADY_int_regslice == 1'b0) | (regslice_both_y_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start = grp_fir_Pipeline_Shift_Accum_Loop_fu_353_ap_start_reg;

assign mul_i29_fu_653_p2 = ($signed(p_shl_cast_fu_637_p1) + $signed(p_shl1_cast_fu_649_p1));

assign p_shl1_cast_fu_649_p1 = $signed(p_shl1_fu_641_p3);

assign p_shl1_fu_641_p3 = {{x_TDATA_int_regslice}, {1'd0}};

assign p_shl_cast_fu_637_p1 = $signed(p_shl_fu_629_p3);

assign p_shl_fu_629_p3 = {{x_TDATA_int_regslice}, {3'd0}};

assign x_TREADY = regslice_both_x_V_data_V_U_ack_in;

assign y_TSTRB_int_regslice = 'bx;

assign y_TVALID = regslice_both_y_V_data_V_U_vld_out;

always @ (posedge ap_clk) begin
    mul_i29_reg_685[0] <= 1'b0;
end

endmodule //fir
