// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_Shift_Accum_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul,
        x,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mul;
input  [31:0] x;
output  [31:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] tmp_1_reg_2481;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] fir_int_int_shift_reg;
wire   [6:0] c_address0;
reg    c_ce0;
wire   [4:0] c_q0;
reg   [31:0] fir_int_int_shift_reg_1;
reg   [31:0] fir_int_int_shift_reg_2;
reg   [31:0] fir_int_int_shift_reg_3;
reg   [31:0] fir_int_int_shift_reg_4;
reg   [31:0] fir_int_int_shift_reg_5;
reg   [31:0] fir_int_int_shift_reg_6;
reg   [31:0] fir_int_int_shift_reg_7;
reg   [31:0] fir_int_int_shift_reg_8;
reg   [31:0] fir_int_int_shift_reg_9;
reg   [31:0] p_ZZ3firPiiE9shift_reg_10;
reg   [31:0] p_ZZ3firPiiE9shift_reg_11;
reg   [31:0] p_ZZ3firPiiE9shift_reg_12;
reg   [31:0] p_ZZ3firPiiE9shift_reg_13;
reg   [31:0] p_ZZ3firPiiE9shift_reg_14;
reg   [31:0] p_ZZ3firPiiE9shift_reg_15;
reg   [31:0] p_ZZ3firPiiE9shift_reg_16;
reg   [31:0] p_ZZ3firPiiE9shift_reg_17;
reg   [31:0] p_ZZ3firPiiE9shift_reg_18;
reg   [31:0] p_ZZ3firPiiE9shift_reg_19;
reg   [31:0] p_ZZ3firPiiE9shift_reg_20;
reg   [31:0] p_ZZ3firPiiE9shift_reg_21;
reg   [31:0] p_ZZ3firPiiE9shift_reg_22;
reg   [31:0] p_ZZ3firPiiE9shift_reg_23;
reg   [31:0] p_ZZ3firPiiE9shift_reg_24;
reg   [31:0] p_ZZ3firPiiE9shift_reg_25;
reg   [31:0] p_ZZ3firPiiE9shift_reg_26;
reg   [31:0] p_ZZ3firPiiE9shift_reg_27;
reg   [31:0] p_ZZ3firPiiE9shift_reg_28;
reg   [31:0] p_ZZ3firPiiE9shift_reg_29;
reg   [31:0] p_ZZ3firPiiE9shift_reg_30;
reg   [31:0] p_ZZ3firPiiE9shift_reg_31;
reg   [31:0] p_ZZ3firPiiE9shift_reg_32;
reg   [31:0] p_ZZ3firPiiE9shift_reg_33;
reg   [31:0] p_ZZ3firPiiE9shift_reg_34;
reg   [31:0] p_ZZ3firPiiE9shift_reg_35;
reg   [31:0] p_ZZ3firPiiE9shift_reg_36;
reg   [31:0] p_ZZ3firPiiE9shift_reg_37;
reg   [31:0] p_ZZ3firPiiE9shift_reg_38;
reg   [31:0] p_ZZ3firPiiE9shift_reg_39;
reg   [31:0] p_ZZ3firPiiE9shift_reg_40;
reg   [31:0] p_ZZ3firPiiE9shift_reg_41;
reg   [31:0] p_ZZ3firPiiE9shift_reg_42;
reg   [31:0] p_ZZ3firPiiE9shift_reg_43;
reg   [31:0] p_ZZ3firPiiE9shift_reg_44;
reg   [31:0] p_ZZ3firPiiE9shift_reg_45;
reg   [31:0] p_ZZ3firPiiE9shift_reg_46;
reg   [31:0] p_ZZ3firPiiE9shift_reg_47;
reg   [31:0] p_ZZ3firPiiE9shift_reg_48;
reg   [31:0] p_ZZ3firPiiE9shift_reg_49;
reg   [31:0] p_ZZ3firPiiE9shift_reg_50;
reg   [31:0] p_ZZ3firPiiE9shift_reg_51;
reg   [31:0] p_ZZ3firPiiE9shift_reg_52;
reg   [31:0] p_ZZ3firPiiE9shift_reg_53;
reg   [31:0] p_ZZ3firPiiE9shift_reg_54;
reg   [31:0] p_ZZ3firPiiE9shift_reg_55;
reg   [31:0] p_ZZ3firPiiE9shift_reg_56;
reg   [31:0] p_ZZ3firPiiE9shift_reg_57;
reg   [31:0] p_ZZ3firPiiE9shift_reg_58;
reg   [31:0] p_ZZ3firPiiE9shift_reg_59;
reg   [31:0] p_ZZ3firPiiE9shift_reg_60;
reg   [31:0] p_ZZ3firPiiE9shift_reg_61;
reg   [31:0] p_ZZ3firPiiE9shift_reg_62;
reg   [31:0] p_ZZ3firPiiE9shift_reg_63;
reg   [31:0] p_ZZ3firPiiE9shift_reg_64;
reg   [31:0] p_ZZ3firPiiE9shift_reg_65;
reg   [31:0] p_ZZ3firPiiE9shift_reg_66;
reg   [31:0] p_ZZ3firPiiE9shift_reg_67;
reg   [31:0] p_ZZ3firPiiE9shift_reg_68;
reg   [31:0] p_ZZ3firPiiE9shift_reg_69;
reg   [31:0] p_ZZ3firPiiE9shift_reg_70;
reg   [31:0] p_ZZ3firPiiE9shift_reg_71;
reg   [31:0] p_ZZ3firPiiE9shift_reg_72;
reg   [31:0] p_ZZ3firPiiE9shift_reg_73;
reg   [31:0] p_ZZ3firPiiE9shift_reg_74;
reg   [31:0] p_ZZ3firPiiE9shift_reg_75;
reg   [31:0] p_ZZ3firPiiE9shift_reg_76;
reg   [31:0] p_ZZ3firPiiE9shift_reg_77;
reg   [31:0] p_ZZ3firPiiE9shift_reg_78;
reg   [31:0] p_ZZ3firPiiE9shift_reg_79;
reg   [31:0] p_ZZ3firPiiE9shift_reg_80;
reg   [31:0] p_ZZ3firPiiE9shift_reg_81;
reg   [31:0] p_ZZ3firPiiE9shift_reg_82;
reg   [31:0] p_ZZ3firPiiE9shift_reg_83;
reg   [31:0] p_ZZ3firPiiE9shift_reg_84;
reg   [31:0] p_ZZ3firPiiE9shift_reg_85;
reg   [31:0] p_ZZ3firPiiE9shift_reg_86;
reg   [31:0] p_ZZ3firPiiE9shift_reg_87;
reg   [31:0] p_ZZ3firPiiE9shift_reg_88;
reg   [31:0] p_ZZ3firPiiE9shift_reg_89;
reg   [31:0] p_ZZ3firPiiE9shift_reg_90;
reg   [31:0] p_ZZ3firPiiE9shift_reg_91;
reg   [31:0] p_ZZ3firPiiE9shift_reg_92;
reg   [31:0] p_ZZ3firPiiE9shift_reg_93;
reg   [31:0] p_ZZ3firPiiE9shift_reg_94;
reg   [31:0] p_ZZ3firPiiE9shift_reg_95;
reg   [31:0] p_ZZ3firPiiE9shift_reg_96;
reg   [31:0] p_ZZ3firPiiE9shift_reg_97;
reg   [31:0] p_ZZ3firPiiE9shift_reg_98;
reg   [31:0] p_ZZ3firPiiE9shift_reg_99;
reg   [31:0] p_ZZ3firPiiE9shift_reg_100;
reg   [31:0] p_ZZ3firPiiE9shift_reg_101;
reg   [31:0] p_ZZ3firPiiE9shift_reg_102;
reg   [31:0] p_ZZ3firPiiE9shift_reg_103;
reg   [31:0] p_ZZ3firPiiE9shift_reg_104;
reg   [31:0] p_ZZ3firPiiE9shift_reg_105;
reg   [31:0] p_ZZ3firPiiE9shift_reg_106;
reg   [31:0] p_ZZ3firPiiE9shift_reg_107;
reg   [31:0] p_ZZ3firPiiE9shift_reg_108;
reg   [31:0] p_ZZ3firPiiE9shift_reg_109;
reg   [31:0] p_ZZ3firPiiE9shift_reg_110;
reg   [31:0] p_ZZ3firPiiE9shift_reg_111;
reg   [31:0] p_ZZ3firPiiE9shift_reg_112;
reg   [31:0] p_ZZ3firPiiE9shift_reg_113;
reg   [31:0] p_ZZ3firPiiE9shift_reg_114;
reg   [31:0] p_ZZ3firPiiE9shift_reg_115;
reg   [31:0] p_ZZ3firPiiE9shift_reg_116;
reg   [31:0] p_ZZ3firPiiE9shift_reg_117;
reg   [31:0] p_ZZ3firPiiE9shift_reg_118;
reg   [31:0] p_ZZ3firPiiE9shift_reg_119;
reg   [31:0] p_ZZ3firPiiE9shift_reg_120;
reg   [31:0] p_ZZ3firPiiE9shift_reg_121;
reg   [31:0] p_ZZ3firPiiE9shift_reg_122;
reg   [31:0] p_ZZ3firPiiE9shift_reg_123;
reg   [31:0] p_ZZ3firPiiE9shift_reg_124;
reg   [31:0] p_ZZ3firPiiE9shift_reg_125;
reg   [31:0] p_ZZ3firPiiE9shift_reg_126;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_1_fu_616_p3;
reg   [0:0] tmp_1_reg_2481_pp0_iter1_reg;
wire   [6:0] trunc_ln19_fu_629_p1;
reg   [6:0] trunc_ln19_reg_2485;
wire   [0:0] icmp_ln28_fu_639_p2;
reg   [0:0] icmp_ln28_reg_2490;
reg   [0:0] icmp_ln28_reg_2490_pp0_iter1_reg;
wire  signed [31:0] tmp_fu_1164_p257;
reg  signed [31:0] tmp_reg_2499;
wire    ap_block_pp0_stage1_11001;
reg  signed [4:0] c_load_reg_2504;
wire   [31:0] grp_fu_2438_p2;
reg   [31:0] mul_ln33_reg_2514;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_mul_pn_phi_fu_597_p4;
reg   [31:0] ap_phi_reg_pp0_iter0_mul_pn_reg_594;
reg   [31:0] ap_phi_reg_pp0_iter1_mul_pn_reg_594;
reg   [31:0] ap_phi_reg_pp0_iter2_mul_pn_reg_594;
wire   [63:0] zext_ln26_fu_624_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
reg   [31:0] acc_fu_554;
wire   [31:0] acc_1_fu_2446_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_558;
wire   [7:0] add_ln19_fu_633_p2;
reg   [7:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_fu_1164_p255;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [6:0] tmp_fu_1164_p1;
wire   [6:0] tmp_fu_1164_p3;
wire   [6:0] tmp_fu_1164_p5;
wire   [6:0] tmp_fu_1164_p7;
wire   [6:0] tmp_fu_1164_p9;
wire   [6:0] tmp_fu_1164_p11;
wire   [6:0] tmp_fu_1164_p13;
wire   [6:0] tmp_fu_1164_p15;
wire   [6:0] tmp_fu_1164_p17;
wire   [6:0] tmp_fu_1164_p19;
wire   [6:0] tmp_fu_1164_p21;
wire   [6:0] tmp_fu_1164_p23;
wire   [6:0] tmp_fu_1164_p25;
wire   [6:0] tmp_fu_1164_p27;
wire   [6:0] tmp_fu_1164_p29;
wire   [6:0] tmp_fu_1164_p31;
wire   [6:0] tmp_fu_1164_p33;
wire   [6:0] tmp_fu_1164_p35;
wire   [6:0] tmp_fu_1164_p37;
wire   [6:0] tmp_fu_1164_p39;
wire   [6:0] tmp_fu_1164_p41;
wire   [6:0] tmp_fu_1164_p43;
wire   [6:0] tmp_fu_1164_p45;
wire   [6:0] tmp_fu_1164_p47;
wire   [6:0] tmp_fu_1164_p49;
wire   [6:0] tmp_fu_1164_p51;
wire   [6:0] tmp_fu_1164_p53;
wire   [6:0] tmp_fu_1164_p55;
wire   [6:0] tmp_fu_1164_p57;
wire   [6:0] tmp_fu_1164_p59;
wire   [6:0] tmp_fu_1164_p61;
wire   [6:0] tmp_fu_1164_p63;
wire   [6:0] tmp_fu_1164_p65;
wire   [6:0] tmp_fu_1164_p67;
wire   [6:0] tmp_fu_1164_p69;
wire   [6:0] tmp_fu_1164_p71;
wire   [6:0] tmp_fu_1164_p73;
wire   [6:0] tmp_fu_1164_p75;
wire   [6:0] tmp_fu_1164_p77;
wire   [6:0] tmp_fu_1164_p79;
wire   [6:0] tmp_fu_1164_p81;
wire   [6:0] tmp_fu_1164_p83;
wire   [6:0] tmp_fu_1164_p85;
wire   [6:0] tmp_fu_1164_p87;
wire   [6:0] tmp_fu_1164_p89;
wire   [6:0] tmp_fu_1164_p91;
wire   [6:0] tmp_fu_1164_p93;
wire   [6:0] tmp_fu_1164_p95;
wire   [6:0] tmp_fu_1164_p97;
wire   [6:0] tmp_fu_1164_p99;
wire   [6:0] tmp_fu_1164_p101;
wire   [6:0] tmp_fu_1164_p103;
wire   [6:0] tmp_fu_1164_p105;
wire   [6:0] tmp_fu_1164_p107;
wire   [6:0] tmp_fu_1164_p109;
wire   [6:0] tmp_fu_1164_p111;
wire   [6:0] tmp_fu_1164_p113;
wire   [6:0] tmp_fu_1164_p115;
wire   [6:0] tmp_fu_1164_p117;
wire   [6:0] tmp_fu_1164_p119;
wire   [6:0] tmp_fu_1164_p121;
wire   [6:0] tmp_fu_1164_p123;
wire   [6:0] tmp_fu_1164_p125;
wire  signed [6:0] tmp_fu_1164_p127;
wire  signed [6:0] tmp_fu_1164_p129;
wire  signed [6:0] tmp_fu_1164_p131;
wire  signed [6:0] tmp_fu_1164_p133;
wire  signed [6:0] tmp_fu_1164_p135;
wire  signed [6:0] tmp_fu_1164_p137;
wire  signed [6:0] tmp_fu_1164_p139;
wire  signed [6:0] tmp_fu_1164_p141;
wire  signed [6:0] tmp_fu_1164_p143;
wire  signed [6:0] tmp_fu_1164_p145;
wire  signed [6:0] tmp_fu_1164_p147;
wire  signed [6:0] tmp_fu_1164_p149;
wire  signed [6:0] tmp_fu_1164_p151;
wire  signed [6:0] tmp_fu_1164_p153;
wire  signed [6:0] tmp_fu_1164_p155;
wire  signed [6:0] tmp_fu_1164_p157;
wire  signed [6:0] tmp_fu_1164_p159;
wire  signed [6:0] tmp_fu_1164_p161;
wire  signed [6:0] tmp_fu_1164_p163;
wire  signed [6:0] tmp_fu_1164_p165;
wire  signed [6:0] tmp_fu_1164_p167;
wire  signed [6:0] tmp_fu_1164_p169;
wire  signed [6:0] tmp_fu_1164_p171;
wire  signed [6:0] tmp_fu_1164_p173;
wire  signed [6:0] tmp_fu_1164_p175;
wire  signed [6:0] tmp_fu_1164_p177;
wire  signed [6:0] tmp_fu_1164_p179;
wire  signed [6:0] tmp_fu_1164_p181;
wire  signed [6:0] tmp_fu_1164_p183;
wire  signed [6:0] tmp_fu_1164_p185;
wire  signed [6:0] tmp_fu_1164_p187;
wire  signed [6:0] tmp_fu_1164_p189;
wire  signed [6:0] tmp_fu_1164_p191;
wire  signed [6:0] tmp_fu_1164_p193;
wire  signed [6:0] tmp_fu_1164_p195;
wire  signed [6:0] tmp_fu_1164_p197;
wire  signed [6:0] tmp_fu_1164_p199;
wire  signed [6:0] tmp_fu_1164_p201;
wire  signed [6:0] tmp_fu_1164_p203;
wire  signed [6:0] tmp_fu_1164_p205;
wire  signed [6:0] tmp_fu_1164_p207;
wire  signed [6:0] tmp_fu_1164_p209;
wire  signed [6:0] tmp_fu_1164_p211;
wire  signed [6:0] tmp_fu_1164_p213;
wire  signed [6:0] tmp_fu_1164_p215;
wire  signed [6:0] tmp_fu_1164_p217;
wire  signed [6:0] tmp_fu_1164_p219;
wire  signed [6:0] tmp_fu_1164_p221;
wire  signed [6:0] tmp_fu_1164_p223;
wire  signed [6:0] tmp_fu_1164_p225;
wire  signed [6:0] tmp_fu_1164_p227;
wire  signed [6:0] tmp_fu_1164_p229;
wire  signed [6:0] tmp_fu_1164_p231;
wire  signed [6:0] tmp_fu_1164_p233;
wire  signed [6:0] tmp_fu_1164_p235;
wire  signed [6:0] tmp_fu_1164_p237;
wire  signed [6:0] tmp_fu_1164_p239;
wire  signed [6:0] tmp_fu_1164_p241;
wire  signed [6:0] tmp_fu_1164_p243;
wire  signed [6:0] tmp_fu_1164_p245;
wire  signed [6:0] tmp_fu_1164_p247;
wire  signed [6:0] tmp_fu_1164_p249;
wire  signed [6:0] tmp_fu_1164_p251;
wire  signed [6:0] tmp_fu_1164_p253;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 fir_int_int_shift_reg = 32'd0;
#0 fir_int_int_shift_reg_1 = 32'd0;
#0 fir_int_int_shift_reg_2 = 32'd0;
#0 fir_int_int_shift_reg_3 = 32'd0;
#0 fir_int_int_shift_reg_4 = 32'd0;
#0 fir_int_int_shift_reg_5 = 32'd0;
#0 fir_int_int_shift_reg_6 = 32'd0;
#0 fir_int_int_shift_reg_7 = 32'd0;
#0 fir_int_int_shift_reg_8 = 32'd0;
#0 fir_int_int_shift_reg_9 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_10 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_11 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_12 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_13 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_14 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_15 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_16 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_17 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_18 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_19 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_20 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_21 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_22 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_23 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_24 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_25 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_26 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_27 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_28 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_29 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_30 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_31 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_32 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_33 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_34 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_35 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_36 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_37 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_38 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_39 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_40 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_41 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_42 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_43 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_44 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_45 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_46 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_47 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_48 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_49 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_50 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_51 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_52 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_53 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_54 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_55 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_56 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_57 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_58 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_59 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_60 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_61 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_62 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_63 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_64 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_65 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_66 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_67 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_68 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_69 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_70 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_71 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_72 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_73 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_74 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_75 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_76 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_77 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_78 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_79 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_80 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_81 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_82 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_83 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_84 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_85 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_86 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_87 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_88 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_89 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_90 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_91 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_92 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_93 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_94 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_95 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_96 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_97 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_98 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_99 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_100 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_101 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_102 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_103 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_104 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_105 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_106 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_107 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_108 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_109 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_110 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_111 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_112 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_113 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_114 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_115 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_116 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_117 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_118 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_119 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_120 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_121 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_122 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_123 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_124 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_125 = 32'd0;
#0 p_ZZ3firPiiE9shift_reg_126 = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 acc_fu_554 = 32'd0;
#0 i_fu_558 = 8'd0;
#0 ap_done_reg = 1'b0;
end

fir_fir_Pipeline_Shift_Accum_Loop_c_ROM_AUTO_1R #(
    .DataWidth( 5 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c_address0),
    .ce0(c_ce0),
    .q0(c_q0)
);

fir_sparsemux_255_7_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 7'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 7'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 7'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 7'h5 ),
    .din4_WIDTH( 32 ),
    .CASE5( 7'h6 ),
    .din5_WIDTH( 32 ),
    .CASE6( 7'h7 ),
    .din6_WIDTH( 32 ),
    .CASE7( 7'h8 ),
    .din7_WIDTH( 32 ),
    .CASE8( 7'h9 ),
    .din8_WIDTH( 32 ),
    .CASE9( 7'hA ),
    .din9_WIDTH( 32 ),
    .CASE10( 7'hB ),
    .din10_WIDTH( 32 ),
    .CASE11( 7'hC ),
    .din11_WIDTH( 32 ),
    .CASE12( 7'hD ),
    .din12_WIDTH( 32 ),
    .CASE13( 7'hE ),
    .din13_WIDTH( 32 ),
    .CASE14( 7'hF ),
    .din14_WIDTH( 32 ),
    .CASE15( 7'h10 ),
    .din15_WIDTH( 32 ),
    .CASE16( 7'h11 ),
    .din16_WIDTH( 32 ),
    .CASE17( 7'h12 ),
    .din17_WIDTH( 32 ),
    .CASE18( 7'h13 ),
    .din18_WIDTH( 32 ),
    .CASE19( 7'h14 ),
    .din19_WIDTH( 32 ),
    .CASE20( 7'h15 ),
    .din20_WIDTH( 32 ),
    .CASE21( 7'h16 ),
    .din21_WIDTH( 32 ),
    .CASE22( 7'h17 ),
    .din22_WIDTH( 32 ),
    .CASE23( 7'h18 ),
    .din23_WIDTH( 32 ),
    .CASE24( 7'h19 ),
    .din24_WIDTH( 32 ),
    .CASE25( 7'h1A ),
    .din25_WIDTH( 32 ),
    .CASE26( 7'h1B ),
    .din26_WIDTH( 32 ),
    .CASE27( 7'h1C ),
    .din27_WIDTH( 32 ),
    .CASE28( 7'h1D ),
    .din28_WIDTH( 32 ),
    .CASE29( 7'h1E ),
    .din29_WIDTH( 32 ),
    .CASE30( 7'h1F ),
    .din30_WIDTH( 32 ),
    .CASE31( 7'h20 ),
    .din31_WIDTH( 32 ),
    .CASE32( 7'h21 ),
    .din32_WIDTH( 32 ),
    .CASE33( 7'h22 ),
    .din33_WIDTH( 32 ),
    .CASE34( 7'h23 ),
    .din34_WIDTH( 32 ),
    .CASE35( 7'h24 ),
    .din35_WIDTH( 32 ),
    .CASE36( 7'h25 ),
    .din36_WIDTH( 32 ),
    .CASE37( 7'h26 ),
    .din37_WIDTH( 32 ),
    .CASE38( 7'h27 ),
    .din38_WIDTH( 32 ),
    .CASE39( 7'h28 ),
    .din39_WIDTH( 32 ),
    .CASE40( 7'h29 ),
    .din40_WIDTH( 32 ),
    .CASE41( 7'h2A ),
    .din41_WIDTH( 32 ),
    .CASE42( 7'h2B ),
    .din42_WIDTH( 32 ),
    .CASE43( 7'h2C ),
    .din43_WIDTH( 32 ),
    .CASE44( 7'h2D ),
    .din44_WIDTH( 32 ),
    .CASE45( 7'h2E ),
    .din45_WIDTH( 32 ),
    .CASE46( 7'h2F ),
    .din46_WIDTH( 32 ),
    .CASE47( 7'h30 ),
    .din47_WIDTH( 32 ),
    .CASE48( 7'h31 ),
    .din48_WIDTH( 32 ),
    .CASE49( 7'h32 ),
    .din49_WIDTH( 32 ),
    .CASE50( 7'h33 ),
    .din50_WIDTH( 32 ),
    .CASE51( 7'h34 ),
    .din51_WIDTH( 32 ),
    .CASE52( 7'h35 ),
    .din52_WIDTH( 32 ),
    .CASE53( 7'h36 ),
    .din53_WIDTH( 32 ),
    .CASE54( 7'h37 ),
    .din54_WIDTH( 32 ),
    .CASE55( 7'h38 ),
    .din55_WIDTH( 32 ),
    .CASE56( 7'h39 ),
    .din56_WIDTH( 32 ),
    .CASE57( 7'h3A ),
    .din57_WIDTH( 32 ),
    .CASE58( 7'h3B ),
    .din58_WIDTH( 32 ),
    .CASE59( 7'h3C ),
    .din59_WIDTH( 32 ),
    .CASE60( 7'h3D ),
    .din60_WIDTH( 32 ),
    .CASE61( 7'h3E ),
    .din61_WIDTH( 32 ),
    .CASE62( 7'h3F ),
    .din62_WIDTH( 32 ),
    .CASE63( 7'h40 ),
    .din63_WIDTH( 32 ),
    .CASE64( 7'h41 ),
    .din64_WIDTH( 32 ),
    .CASE65( 7'h42 ),
    .din65_WIDTH( 32 ),
    .CASE66( 7'h43 ),
    .din66_WIDTH( 32 ),
    .CASE67( 7'h44 ),
    .din67_WIDTH( 32 ),
    .CASE68( 7'h45 ),
    .din68_WIDTH( 32 ),
    .CASE69( 7'h46 ),
    .din69_WIDTH( 32 ),
    .CASE70( 7'h47 ),
    .din70_WIDTH( 32 ),
    .CASE71( 7'h48 ),
    .din71_WIDTH( 32 ),
    .CASE72( 7'h49 ),
    .din72_WIDTH( 32 ),
    .CASE73( 7'h4A ),
    .din73_WIDTH( 32 ),
    .CASE74( 7'h4B ),
    .din74_WIDTH( 32 ),
    .CASE75( 7'h4C ),
    .din75_WIDTH( 32 ),
    .CASE76( 7'h4D ),
    .din76_WIDTH( 32 ),
    .CASE77( 7'h4E ),
    .din77_WIDTH( 32 ),
    .CASE78( 7'h4F ),
    .din78_WIDTH( 32 ),
    .CASE79( 7'h50 ),
    .din79_WIDTH( 32 ),
    .CASE80( 7'h51 ),
    .din80_WIDTH( 32 ),
    .CASE81( 7'h52 ),
    .din81_WIDTH( 32 ),
    .CASE82( 7'h53 ),
    .din82_WIDTH( 32 ),
    .CASE83( 7'h54 ),
    .din83_WIDTH( 32 ),
    .CASE84( 7'h55 ),
    .din84_WIDTH( 32 ),
    .CASE85( 7'h56 ),
    .din85_WIDTH( 32 ),
    .CASE86( 7'h57 ),
    .din86_WIDTH( 32 ),
    .CASE87( 7'h58 ),
    .din87_WIDTH( 32 ),
    .CASE88( 7'h59 ),
    .din88_WIDTH( 32 ),
    .CASE89( 7'h5A ),
    .din89_WIDTH( 32 ),
    .CASE90( 7'h5B ),
    .din90_WIDTH( 32 ),
    .CASE91( 7'h5C ),
    .din91_WIDTH( 32 ),
    .CASE92( 7'h5D ),
    .din92_WIDTH( 32 ),
    .CASE93( 7'h5E ),
    .din93_WIDTH( 32 ),
    .CASE94( 7'h5F ),
    .din94_WIDTH( 32 ),
    .CASE95( 7'h60 ),
    .din95_WIDTH( 32 ),
    .CASE96( 7'h61 ),
    .din96_WIDTH( 32 ),
    .CASE97( 7'h62 ),
    .din97_WIDTH( 32 ),
    .CASE98( 7'h63 ),
    .din98_WIDTH( 32 ),
    .CASE99( 7'h64 ),
    .din99_WIDTH( 32 ),
    .CASE100( 7'h65 ),
    .din100_WIDTH( 32 ),
    .CASE101( 7'h66 ),
    .din101_WIDTH( 32 ),
    .CASE102( 7'h67 ),
    .din102_WIDTH( 32 ),
    .CASE103( 7'h68 ),
    .din103_WIDTH( 32 ),
    .CASE104( 7'h69 ),
    .din104_WIDTH( 32 ),
    .CASE105( 7'h6A ),
    .din105_WIDTH( 32 ),
    .CASE106( 7'h6B ),
    .din106_WIDTH( 32 ),
    .CASE107( 7'h6C ),
    .din107_WIDTH( 32 ),
    .CASE108( 7'h6D ),
    .din108_WIDTH( 32 ),
    .CASE109( 7'h6E ),
    .din109_WIDTH( 32 ),
    .CASE110( 7'h6F ),
    .din110_WIDTH( 32 ),
    .CASE111( 7'h70 ),
    .din111_WIDTH( 32 ),
    .CASE112( 7'h71 ),
    .din112_WIDTH( 32 ),
    .CASE113( 7'h72 ),
    .din113_WIDTH( 32 ),
    .CASE114( 7'h73 ),
    .din114_WIDTH( 32 ),
    .CASE115( 7'h74 ),
    .din115_WIDTH( 32 ),
    .CASE116( 7'h75 ),
    .din116_WIDTH( 32 ),
    .CASE117( 7'h76 ),
    .din117_WIDTH( 32 ),
    .CASE118( 7'h77 ),
    .din118_WIDTH( 32 ),
    .CASE119( 7'h78 ),
    .din119_WIDTH( 32 ),
    .CASE120( 7'h79 ),
    .din120_WIDTH( 32 ),
    .CASE121( 7'h7A ),
    .din121_WIDTH( 32 ),
    .CASE122( 7'h7B ),
    .din122_WIDTH( 32 ),
    .CASE123( 7'h7C ),
    .din123_WIDTH( 32 ),
    .CASE124( 7'h7D ),
    .din124_WIDTH( 32 ),
    .CASE125( 7'h7E ),
    .din125_WIDTH( 32 ),
    .CASE126( 7'h7F ),
    .din126_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
sparsemux_255_7_32_1_1_U1(
    .din0(fir_int_int_shift_reg),
    .din1(fir_int_int_shift_reg_1),
    .din2(fir_int_int_shift_reg_2),
    .din3(fir_int_int_shift_reg_3),
    .din4(fir_int_int_shift_reg_4),
    .din5(fir_int_int_shift_reg_5),
    .din6(fir_int_int_shift_reg_6),
    .din7(fir_int_int_shift_reg_7),
    .din8(fir_int_int_shift_reg_8),
    .din9(fir_int_int_shift_reg_9),
    .din10(p_ZZ3firPiiE9shift_reg_10),
    .din11(p_ZZ3firPiiE9shift_reg_11),
    .din12(p_ZZ3firPiiE9shift_reg_12),
    .din13(p_ZZ3firPiiE9shift_reg_13),
    .din14(p_ZZ3firPiiE9shift_reg_14),
    .din15(p_ZZ3firPiiE9shift_reg_15),
    .din16(p_ZZ3firPiiE9shift_reg_16),
    .din17(p_ZZ3firPiiE9shift_reg_17),
    .din18(p_ZZ3firPiiE9shift_reg_18),
    .din19(p_ZZ3firPiiE9shift_reg_19),
    .din20(p_ZZ3firPiiE9shift_reg_20),
    .din21(p_ZZ3firPiiE9shift_reg_21),
    .din22(p_ZZ3firPiiE9shift_reg_22),
    .din23(p_ZZ3firPiiE9shift_reg_23),
    .din24(p_ZZ3firPiiE9shift_reg_24),
    .din25(p_ZZ3firPiiE9shift_reg_25),
    .din26(p_ZZ3firPiiE9shift_reg_26),
    .din27(p_ZZ3firPiiE9shift_reg_27),
    .din28(p_ZZ3firPiiE9shift_reg_28),
    .din29(p_ZZ3firPiiE9shift_reg_29),
    .din30(p_ZZ3firPiiE9shift_reg_30),
    .din31(p_ZZ3firPiiE9shift_reg_31),
    .din32(p_ZZ3firPiiE9shift_reg_32),
    .din33(p_ZZ3firPiiE9shift_reg_33),
    .din34(p_ZZ3firPiiE9shift_reg_34),
    .din35(p_ZZ3firPiiE9shift_reg_35),
    .din36(p_ZZ3firPiiE9shift_reg_36),
    .din37(p_ZZ3firPiiE9shift_reg_37),
    .din38(p_ZZ3firPiiE9shift_reg_38),
    .din39(p_ZZ3firPiiE9shift_reg_39),
    .din40(p_ZZ3firPiiE9shift_reg_40),
    .din41(p_ZZ3firPiiE9shift_reg_41),
    .din42(p_ZZ3firPiiE9shift_reg_42),
    .din43(p_ZZ3firPiiE9shift_reg_43),
    .din44(p_ZZ3firPiiE9shift_reg_44),
    .din45(p_ZZ3firPiiE9shift_reg_45),
    .din46(p_ZZ3firPiiE9shift_reg_46),
    .din47(p_ZZ3firPiiE9shift_reg_47),
    .din48(p_ZZ3firPiiE9shift_reg_48),
    .din49(p_ZZ3firPiiE9shift_reg_49),
    .din50(p_ZZ3firPiiE9shift_reg_50),
    .din51(p_ZZ3firPiiE9shift_reg_51),
    .din52(p_ZZ3firPiiE9shift_reg_52),
    .din53(p_ZZ3firPiiE9shift_reg_53),
    .din54(p_ZZ3firPiiE9shift_reg_54),
    .din55(p_ZZ3firPiiE9shift_reg_55),
    .din56(p_ZZ3firPiiE9shift_reg_56),
    .din57(p_ZZ3firPiiE9shift_reg_57),
    .din58(p_ZZ3firPiiE9shift_reg_58),
    .din59(p_ZZ3firPiiE9shift_reg_59),
    .din60(p_ZZ3firPiiE9shift_reg_60),
    .din61(p_ZZ3firPiiE9shift_reg_61),
    .din62(p_ZZ3firPiiE9shift_reg_62),
    .din63(p_ZZ3firPiiE9shift_reg_63),
    .din64(p_ZZ3firPiiE9shift_reg_64),
    .din65(p_ZZ3firPiiE9shift_reg_65),
    .din66(p_ZZ3firPiiE9shift_reg_66),
    .din67(p_ZZ3firPiiE9shift_reg_67),
    .din68(p_ZZ3firPiiE9shift_reg_68),
    .din69(p_ZZ3firPiiE9shift_reg_69),
    .din70(p_ZZ3firPiiE9shift_reg_70),
    .din71(p_ZZ3firPiiE9shift_reg_71),
    .din72(p_ZZ3firPiiE9shift_reg_72),
    .din73(p_ZZ3firPiiE9shift_reg_73),
    .din74(p_ZZ3firPiiE9shift_reg_74),
    .din75(p_ZZ3firPiiE9shift_reg_75),
    .din76(p_ZZ3firPiiE9shift_reg_76),
    .din77(p_ZZ3firPiiE9shift_reg_77),
    .din78(p_ZZ3firPiiE9shift_reg_78),
    .din79(p_ZZ3firPiiE9shift_reg_79),
    .din80(p_ZZ3firPiiE9shift_reg_80),
    .din81(p_ZZ3firPiiE9shift_reg_81),
    .din82(p_ZZ3firPiiE9shift_reg_82),
    .din83(p_ZZ3firPiiE9shift_reg_83),
    .din84(p_ZZ3firPiiE9shift_reg_84),
    .din85(p_ZZ3firPiiE9shift_reg_85),
    .din86(p_ZZ3firPiiE9shift_reg_86),
    .din87(p_ZZ3firPiiE9shift_reg_87),
    .din88(p_ZZ3firPiiE9shift_reg_88),
    .din89(p_ZZ3firPiiE9shift_reg_89),
    .din90(p_ZZ3firPiiE9shift_reg_90),
    .din91(p_ZZ3firPiiE9shift_reg_91),
    .din92(p_ZZ3firPiiE9shift_reg_92),
    .din93(p_ZZ3firPiiE9shift_reg_93),
    .din94(p_ZZ3firPiiE9shift_reg_94),
    .din95(p_ZZ3firPiiE9shift_reg_95),
    .din96(p_ZZ3firPiiE9shift_reg_96),
    .din97(p_ZZ3firPiiE9shift_reg_97),
    .din98(p_ZZ3firPiiE9shift_reg_98),
    .din99(p_ZZ3firPiiE9shift_reg_99),
    .din100(p_ZZ3firPiiE9shift_reg_100),
    .din101(p_ZZ3firPiiE9shift_reg_101),
    .din102(p_ZZ3firPiiE9shift_reg_102),
    .din103(p_ZZ3firPiiE9shift_reg_103),
    .din104(p_ZZ3firPiiE9shift_reg_104),
    .din105(p_ZZ3firPiiE9shift_reg_105),
    .din106(p_ZZ3firPiiE9shift_reg_106),
    .din107(p_ZZ3firPiiE9shift_reg_107),
    .din108(p_ZZ3firPiiE9shift_reg_108),
    .din109(p_ZZ3firPiiE9shift_reg_109),
    .din110(p_ZZ3firPiiE9shift_reg_110),
    .din111(p_ZZ3firPiiE9shift_reg_111),
    .din112(p_ZZ3firPiiE9shift_reg_112),
    .din113(p_ZZ3firPiiE9shift_reg_113),
    .din114(p_ZZ3firPiiE9shift_reg_114),
    .din115(p_ZZ3firPiiE9shift_reg_115),
    .din116(p_ZZ3firPiiE9shift_reg_116),
    .din117(p_ZZ3firPiiE9shift_reg_117),
    .din118(p_ZZ3firPiiE9shift_reg_118),
    .din119(p_ZZ3firPiiE9shift_reg_119),
    .din120(p_ZZ3firPiiE9shift_reg_120),
    .din121(p_ZZ3firPiiE9shift_reg_121),
    .din122(p_ZZ3firPiiE9shift_reg_122),
    .din123(p_ZZ3firPiiE9shift_reg_123),
    .din124(p_ZZ3firPiiE9shift_reg_124),
    .din125(p_ZZ3firPiiE9shift_reg_125),
    .din126(p_ZZ3firPiiE9shift_reg_126),
    .def(tmp_fu_1164_p255),
    .sel(trunc_ln19_reg_2485),
    .dout(tmp_fu_1164_p257)
);

fir_mul_5s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_5s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(c_load_reg_2504),
    .din1(tmp_reg_2499),
    .ce(1'b1),
    .dout(grp_fu_2438_p2)
);

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_fu_554 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            acc_fu_554 <= acc_1_fu_2446_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_1_fu_616_p3 == 1'd0))) begin
            i_fu_558 <= add_ln19_fu_633_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_558 <= 8'd127;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_fu_639_p2 == 1'd1) & (tmp_1_fu_616_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter0_mul_pn_reg_594 <= mul;
        fir_int_int_shift_reg <= x;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_mul_pn_reg_594 <= ap_phi_reg_pp0_iter0_mul_pn_reg_594;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter2_mul_pn_reg_594 <= ap_phi_reg_pp0_iter1_mul_pn_reg_594;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_load_reg_2504 <= c_q0;
        mul_ln33_reg_2514 <= grp_fu_2438_p2;
        tmp_reg_2499 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_1 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_2 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_3 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd4) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_4 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd5) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_5 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd6) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_6 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd7) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_7 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd8) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_8 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd9) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fir_int_int_shift_reg_9 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln28_reg_2490 <= icmp_ln28_fu_639_p2;
        icmp_ln28_reg_2490_pp0_iter1_reg <= icmp_ln28_reg_2490;
        tmp_1_reg_2481 <= ap_sig_allocacmp_i_1[32'd7];
        tmp_1_reg_2481_pp0_iter1_reg <= tmp_1_reg_2481;
        trunc_ln19_reg_2485 <= trunc_ln19_fu_629_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd10) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_10 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd100) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_100 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd101) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_101 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_102 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd103) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_103 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd104) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_104 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd105) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_105 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd106) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_106 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd107) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_107 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd108) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_108 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd109) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_109 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd11) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_11 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd110) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_110 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd111) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_111 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd112) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_112 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd113) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_113 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd114) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_114 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd115) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_115 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd116) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_116 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd117) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_117 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd118) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_118 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd119) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_119 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd12) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_12 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd120) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_120 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd121) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_121 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd122) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_122 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd123) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_123 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd124) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_124 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd125) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_125 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd126) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_126 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd13) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_13 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd14) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_14 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd15) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_15 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd16) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_16 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd17) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_17 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd18) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_18 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd19) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_19 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd20) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_20 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd21) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_21 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd22) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_22 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd23) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_23 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd24) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_24 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd25) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_25 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd26) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_26 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd27) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_27 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd28) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_28 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd29) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_29 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd30) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_30 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd31) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_31 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd32) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_32 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd33) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_33 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd34) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_34 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd35) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_35 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd36) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_36 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd37) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_37 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd38) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_38 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd39) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_39 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd40) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_40 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd41) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_41 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd42) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_42 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd43) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_43 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd44) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_44 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd45) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_45 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd46) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_46 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd47) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_47 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd48) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_48 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd49) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_49 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd50) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_50 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd51) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_51 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd52) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_52 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd53) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_53 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd54) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_54 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd55) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_55 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd56) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_56 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd57) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_57 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd58) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_58 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd59) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_59 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd60) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_60 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd61) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_61 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd62) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_62 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd63) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_63 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd64) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_64 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd65) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_65 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd66) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_66 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd67) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_67 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd68) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_68 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd69) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_69 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd70) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_70 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd71) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_71 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd72) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_72 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd73) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_73 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd74) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_74 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd75) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_75 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd76) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_76 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd77) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_77 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd78) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_78 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd79) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_79 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd80) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_80 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd81) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_81 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd82) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_82 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd83) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_83 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd84) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_84 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd85) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_85 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd86) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_86 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd87) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_87 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd88) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_88 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd89) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_89 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd90) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_90 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd91) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_91 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd92) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_92 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd93) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_93 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd94) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_94 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd95) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_95 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd96) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_96 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd97) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_97 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd98) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_98 <= tmp_fu_1164_p257;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_2481 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln28_reg_2490 == 1'd0) & (trunc_ln19_reg_2485 == 7'd99) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZZ3firPiiE9shift_reg_99 <= tmp_fu_1164_p257;
    end
end

always @ (*) begin
    if (((tmp_1_reg_2481 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_2481 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_2481 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln28_reg_2490_pp0_iter1_reg == 1'd0) & (tmp_1_reg_2481_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_mul_pn_phi_fu_597_p4 = mul_ln33_reg_2514;
    end else begin
        ap_phi_mux_mul_pn_phi_fu_597_p4 = ap_phi_reg_pp0_iter2_mul_pn_reg_594;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 8'd127;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_558;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter1_stage0) & (ap_idle_pp0_0to0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_2446_p2 = (ap_phi_mux_mul_pn_phi_fu_597_p4 + acc_fu_554);

assign acc_out = acc_fu_554;

assign add_ln19_fu_633_p2 = ($signed(ap_sig_allocacmp_i_1) + $signed(8'd255));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign c_address0 = zext_ln26_fu_624_p1;

assign icmp_ln28_fu_639_p2 = ((ap_sig_allocacmp_i_1 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_1_fu_616_p3 = ap_sig_allocacmp_i_1[32'd7];

assign tmp_fu_1164_p255 = 'bx;

assign trunc_ln19_fu_629_p1 = ap_sig_allocacmp_i_1[6:0];

assign zext_ln26_fu_624_p1 = ap_sig_allocacmp_i_1;

endmodule //fir_fir_Pipeline_Shift_Accum_Loop
